version: "3.6"
services:
  postgres:
    image: postgres:12
    ports:
    - "5432:5432"
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
  graphql-engine:
    image: hasura/graphql-engine:v1.3.3
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false" # set to "false" if you use hasura CLI
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_GRAPHQL_ADMIN_SECRET}"
      HASURA_GRAPHQL_JWT_SECRET: '{jwk_url": "http://hasura-backend-plus:3000/auth/jwks"}'
      # HASURA_GRAPHQL_JWT_SECRET: '{"jwk_url": "http://host.docker.internal:3000/auth/jwks"}'
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: public
  hasura-backend-plus:
    image: jegoruglov/hasura-backend-plus
    ports:
      - "3000:3000"
    environment:
      SERVER_URL: http://localhost:3000
      HASURA_ENDPOINT: http://graphql-engine:8080/v1/graphql
      HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_GRAPHQL_ADMIN_SECRET}"
      JWT_ALGORITHM: RS256
      S3_ENDPOINT: http://minio:9000
      S3_BUCKET: "${S3_BUCKET}"
      S3_ACCESS_KEY_ID: "${S3_ACCESS_KEY_ID}"
      S3_SECRET_ACCESS_KEY: "${S3_SECRET_ACCESS_KEY}"
      AUTO_MIGRATE: "true"
      MIN_PASSWORD_LENGTH: 8
      GOOGLE_ENABLE: "true"
      GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
      GOOGLE_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET}"
      PROVIDER_SUCCESS_REDIRECT: "${PROVIDER_SUCCESS_REDIRECT}"
      PROVIDER_FAILURE_REDIRECT: "${PROVIDER_FAILURE_REDIRECT}"
      PIPEDRIVE_ENABLE: "true"
      PIPEDRIVE_CLIENT_ID: "${PIPEDRIVE_CLIENT_ID}"
      PIPEDRIVE_CLIENT_SECRET: "${PIPEDRIVE_CLIENT_SECRET}"
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    restart: always
    environment:
      S3_BUCKET: "${S3_BUCKET}"
      MINIO_ACCESS_KEY: "${S3_ACCESS_KEY_ID}"
      MINIO_SECRET_KEY: "${S3_SECRET_ACCESS_KEY}" ## min 8 character
    entrypoint: sh
    command: "-c 'mkdir -p /export/hasura-backend-plus && /usr/bin/minio server /export'"
    volumes:
      - "minio_data:/data"
volumes:
  db_data:
  minio_data:

