version: '3.6'
services:
  postgres:
    image: postgres:12
    ports:
    - "54320:5432"
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: postgres
  graphql-engine:
    image: hasura/graphql-engine:v1.3.3
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: XpjezMXU3VLhDDS82fUoiMWTXoLcEEG9
      # HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS256", "jwk_url": "http://hasura-backend-plus:3000/auth/jwks"}'
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS256", "jwk_url": "http://host.docker.internal:3000/auth/jwks"}'
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: public
  hasura-backend-plus:
    image: nhost/hasura-backend-plus:latest
    ports:
      - '3000:3000'
    environment:
      SERVER_URL: http://localhost:3000
      HASURA_ENDPOINT: http://graphql-engine:8080/v1/graphql
      #HASURA_GRAPHQL_ADMIN_SECRET: '$HASURA_GRAPHQL_ADMIN_SECRET'
      HASURA_GRAPHQL_ADMIN_SECRET: XpjezMXU3VLhDDS82fUoiMWTXoLcEEG9
      JWT_ALGORITHM: RS256
      S3_ENDPOINT: http://minio:9000
      S3_BUCKET: hasura-backend-plus
      S3_ACCESS_KEY_ID: minio_access_key
      #S3_SECRET_ACCESS_KEY: '${S3_SECRET_ACCESS_KEY:?S3_SECRET_ACCESS_KEY}'
      S3_SECRET_ACCESS_KEY: XqvRRwH/MP++aIiMGrb8QsRW/4kZmyKZpimHr0bU
      AUTO_MIGRATE: "true"
      MIN_PASSWORD_LENGTH: 8
      # ALLOW_USER_SELF_DELETE: "true"
      # EMAILS_ENABLE: "true"
      # LOST_PASSWORD_ENABLE: "true"
      # SMTP_HOST: smtp.postmarkapp.com
      # SMTP_PORT: 2525
      # SMTP_USER: d12cc014-7190-4558-842c-f51bbba4efc3
      # SMTP_PASS: d12cc014-7190-4558-842c-f51bbba4efc3
      # SMTP_SECURE: "false"
      # SMTP_SENDER: "hello@beautifulthins.ee"
      # AUTO_ACTIVATE_NEW_USERS: "true"
      # SPOTIFY_ENABLE: "true"
      # SPOTIFY_CLIENT_ID: f1f8c3038db147c8bffa231044a40c58
      # SPOTIFY_CLIENT_SECRET: d17b466fbdbe4655a71724b4da3ead46
  minio:
    image: minio/minio
    ports:
      - '9000:9000'
    restart: always
    environment:
      S3_BUCKET: hasura-backend-plus
      MINIO_ACCESS_KEY: minio_access_key
      #MINIO_SECRET_KEY: '${S3_SECRET_ACCESS_KEY:?S3_SECRET_ACCESS_KEY}' ## min 8 character
      MINIO_SECRET_KEY: XqvRRwH/MP++aIiMGrb8QsRW/4kZmyKZpimHr0bU
    entrypoint: sh
    command: "-c 'mkdir -p /export/hasura-backend-plus && /usr/bin/minio server /export'"
    volumes:
      - 'minio_data:/data'
volumes:
  db_data:
  minio_data:

#HASURA_GRAPHQL_ADMIN_SECRET=XpjezMXU3VLhDDS82fUoiMWTXoLcEEG9
#S3_SECRET_ACCESS_KEY=XqvRRwH/MP++aIiMGrb8QsRW/4kZmyKZpimHr0bU